### ISSUE TITLE
Add time server parameter

### ISSUE THREAD

**Issue by leshkinski** [rsWinAutomationSupport/rsInternationalSettings#2]
the rsTime resource can potentially accept a time server parameter to deploy on the managed nodes in addition to the mandatory time zone setting

**Comment by jonathan-madison** [comment]
Shouldn't this be possible with the Registry built-in DSC resource? Not that I'm opposed to having it in a module but since it can be set in the registry it may not be worth your time.

**Comment by leshkinski** [comment]
True, but it would be a simple thing to add and seeing as this setting is closely related to the localisation module, it makes sense to add this parameter.

I'd prefer to use dedicated modules for settings over direct registry change simply because it makes configs cleaner and much easier for support to implement. I have a feeling MS included the registry module as a catch-all for any settings that don't have a dedicated module yet.

**Comment by jonathan-madison** [comment]
Works for me, I was just pointing it out in case it hadn't been considered. :)
